import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { ToolJetClient } from '../src/tooljetClient.js';
import { lintAppSpecTool } from '../src/tools/lintAppSpec.js';
import { clearAppPlansForTests } from '../src/appPlanStore.js';

function textOf(result: { content: Array<{ text: string }> }): any {
  return JSON.parse(result.content[0]!.text);
}

describe('lint_app_spec', () => {
  beforeEach(() => clearAppPlansForTests());

  it('validates a complete planned flow through logical refs without writing', async () => {
    const client = {
      listDatasources: vi.fn().mockResolvedValue([{ id: 'tjdb', name: 'ToolJet DB', kind: 'tooljetdb' }]),
      listTables: vi.fn().mockResolvedValue([]),
    } as unknown as ToolJetClient;
    const result = await lintAppSpecTool(client).handler({
      version_id: 'v1',
      tables: [{ table_name: 'cases', columns: [{ name: 'title', type: 'string' }] }],
      queries: [
        { client_ref: 'list', datasource_id: 'tjdb', name: 'list_cases', options: { operation: 'list_rows', table_id: 't1', list_rows: {} } },
        {
          client_ref: 'create', datasource_id: 'tjdb', name: 'create_case',
          options: { operation: 'create_row', table_id: 't1', create_row: { 0: { column: 'title', value: '{{components.caseTitle.value}}' } } },
        },
      ],
      pages: [{
        client_ref: 'home', name: 'Home', icon: 'IconHome2',
        components: [
          {
            client_ref: 'caseTitle', name: 'caseTitle', type: 'TextInput',
            properties: { label: { value: 'Title' } }, styles: { alignment: { value: 'top' } },
            layout: { top: 20, left: 2, width: 20, height: 60 },
          },
          {
            client_ref: 'save', name: 'saveCase', type: 'Button', properties: { text: { value: 'Save' } },
            layout: { top: 120, left: 2, width: 6, height: 40 },
          },
        ],
      }],
      events: [{
        source_ref: 'save', source_type: 'component', trigger: 'onClick',
        action: { actionId: 'run-query', target_ref: 'create' },
      }],
      lifecycles: [{
        query_ref: 'create', refresh_query_refs: ['list'], clear_component_refs: ['caseTitle'],
        success_alert: { message: 'Created' }, failure_alert: { message: 'Failed' },
      }],
    });
    const body = textOf(result);
    expect(body.ok).toBe(true);
    expect(body.counts).toMatchObject({ tables: 1, seed_rows: 0, pages: 1, components: 2, queries: 2, events: 5, lifecycles: 1 });
    expect(body.plan_token).toEqual(expect.any(String));
    expect(client.listDatasources).toHaveBeenCalledOnce();
  });

  it('uses existing app context for repair bindings and event targets', async () => {
    const client = {
      getAppSummary: vi.fn().mockResolvedValue({
        app_id: 'app1', name: 'Returns', version_id: 'v1',
        pages: [{ id: 'home-id', name: 'Home', handle: 'home', icon: 'IconHome2', components: [] }],
        queries: [{
          id: 'returns-id', name: 'returnsPage', kind: 'tooljetdb', data_source_id: 'tjdb',
          options: { operation: 'list_rows', table_id: 'returns-table', list_rows: { limit: 7 } },
        }],
        events: [],
      }),
    } as unknown as ToolJetClient;

    const result = await lintAppSpecTool(client).handler({
      app_id: 'app1',
      version_id: 'v1',
      pages: [{
        client_ref: 'home', name: 'Home', icon: 'IconHome2',
        components: [
          {
            client_ref: 'count', name: 'returnCount', type: 'Text',
            properties: { text: '{{queries.returnsPage.data.length}}' },
            layout: { top: 20, left: 2, width: 12, height: 40 },
          },
          {
            client_ref: 'refresh', name: 'refreshReturns', type: 'Button',
            properties: { text: 'Refresh' }, layout: { top: 80, left: 2, width: 6, height: 40 },
          },
        ],
      }],
      events: [{
        source_ref: 'refresh', source_type: 'component', trigger: 'onClick',
        action: { actionId: 'run-query', target_ref: 'returnsPage' },
      }],
    });

    const body = textOf(result);
    expect(body.ok).toBe(true);
    expect(body.counts).toMatchObject({ pages: 1, components: 2, queries: 0, events: 1 });
    expect(body.warnings.join(' ')).not.toMatch(/no query is named "returnsPage"/i);
    expect(client.getAppSummary).toHaveBeenCalledWith('app1');
  });

  it('does not duplicate planned switch-page handlers into persisted chains', async () => {
    const client = {
      getAppSummary: vi.fn().mockResolvedValue({
        app_id: 'app1', name: 'Returns', version_id: 'v1',
        pages: [{
          id: 'queue-id', name: 'Returns Queue', handle: 'returns-queue', icon: 'IconListDetails',
          components: [{
            id: 'table-id', name: 'returnsTable', type: 'Table',
            properties: {
              columns: { value: [{
                id: 'actions', name: 'Actions', key: 'actions', columnType: 'button',
                autogenerated: false, buttons: [{ id: 'review', buttonLabel: 'Review' }],
              }] },
            },
          }],
        }],
        queries: [],
        events: [{
          id: 'alert-id', name: 'Review selected', sourceId: 'table-id', target: 'table_column', index: 0,
          event: { eventId: 'onClick', ref: 'actions::review', actionId: 'show-alert', message: 'Opening', alertType: 'info' },
        }],
      }),
    } as unknown as ToolJetClient;

    const result = await lintAppSpecTool(client).handler({
      app_id: 'app1', version_id: 'v1',
      pages: [{
        client_ref: 'review-page', name: 'Return Review', icon: 'IconClipboardCheck', hidden: true,
        components: [{
          client_ref: 'back', name: 'backToQueue', type: 'Button', properties: { text: 'Back' },
          layout: { top: 20, left: 2, width: 8, height: 40 },
        }],
      }],
      events: [
        {
          source_ref: 'returnsTable', source_type: 'table_column', ref: 'actions::review', trigger: 'onClick',
          action: { actionId: 'switch-page', target_ref: 'review-page' }, name: 'Open return review',
        },
        {
          source_ref: 'back', source_type: 'component', trigger: 'onClick',
          action: { actionId: 'switch-page', target_ref: 'Returns Queue' }, name: 'Back to returns queue',
        },
      ],
    });

    const body = textOf(result);
    expect(body.ok).toBe(true);
    expect(body.errors).toEqual([]);
  });

  it('collects mechanical failures across tables, components, queries, and events in one pass', async () => {
    const client = { listDatasources: vi.fn(), listTables: vi.fn().mockResolvedValue([]) } as unknown as ToolJetClient;
    const result = await lintAppSpecTool(client).handler({
      tables: [{ table_name: 'steps', columns: [{ name: 'action', type: 'string' }] }],
      queries: [{ datasource_id: 'tjdb', kind: 'tooljetdb', name: 'bad_query', options: { operation: 'list_rows', table_id: 't1', order_filters: [] } }],
      pages: [{
        name: 'Cases', icon: 'IconChecklist',
        components: [
          {
            client_ref: 'title', name: 'title', type: 'Text', properties: { text: { value: 'Large heading' } },
            styles: { textSize: { value: 32 }, fontWeight: { value: 'bold' } },
            layout: { top: 0, left: 0, width: 20, height: 40 },
          },
          {
            client_ref: 'save', name: 'save', type: 'Button', properties: { text: { value: 'Save' } },
            layout: { top: 60, left: 0, width: 6, height: 40 },
          },
        ],
      }],
      events: [{
        source_ref: 'save', source_type: 'component', trigger: 'onChange',
        action: { actionId: 'run-query', target_ref: 'missing' },
      }],
    });
    const body = textOf(result);
    expect(body.ok).toBe(false);
    expect(body.errors.join(' ')).toMatch(/reserved column name/i);
    expect(body.errors.join(' ')).toMatch(/unknown.*target_ref/i);
    expect(body.errors.join(' ')).toMatch(/trigger "onChange" is not valid for Button/i);
    expect(body.warnings.join(' ')).toMatch(/order_filters|Unknown option key/i);
    expect(body.warnings.join(' ')).toMatch(/too short.*single line needs/i);
  });

  it('requires at least one spec section', async () => {
    const result = await lintAppSpecTool({} as ToolJetClient).handler({});
    expect(result.isError).toBe(true);
    expect(result.content[0]!.text).toMatch(/at least one table, seed_data batch, query, page, event, or lifecycle/i);
  });
});
