import { describe, it, expect } from 'vitest';
import { getCatalog, getComponentSchema } from '../src/catalog.js';
import { FORM_SCHEMA_FIELD_TYPES, SAFE_GENERATED_FORM_FIELD_TYPES } from '../src/formFieldTypes.js';

describe('catalog', () => {
  it('palette lists the built-in components incl. Table and Statistics', () => {
    const types = getCatalog().map((c) => c.type);
    expect(types).toContain('Table');
    expect(types).toContain('Statistics');
    expect(types.length).toBeGreaterThanOrEqual(80);
    // every entry carries a purpose
    expect(getCatalog().every((c) => typeof c.type === 'string')).toBe(true);
  });

  it('includes source-harvested events, actions, exposed variables, and style metadata', () => {
    const table = getComponentSchema('Table')!;
    expect(table.events?.map((event) => event.id)).toEqual(
      expect.arrayContaining(['onPageChanged', 'onSearch', 'onSort', 'onFilterChanged', 'onBulkUpdate'])
    );
    expect(table.actions?.map((action) => action.handle)).toEqual(
      expect.arrayContaining(['setPage', 'selectRow', 'downloadTableData'])
    );
    expect(table.exposedVariables?.map((variable) => variable.name)).toEqual(
      expect.arrayContaining(['pageIndex', 'searchText', 'filters', 'currentPageData'])
    );
    expect(table.styles.some((style) => style.label && ('valueType' in style || 'default' in style))).toBe(true);

    const form = getComponentSchema('Form')!;
    expect(form.events?.map((event) => event.id)).toEqual(expect.arrayContaining(['onSubmit', 'onInvalid']));
    expect(form.actions?.map((action) => action.handle)).toEqual(expect.arrayContaining(['submitForm', 'resetForm']));
    expect(form.exposedVariables?.map((variable) => variable.name)).toContain('formData');
    expect(form.defaultChildren?.length).toBeGreaterThan(0);
  });

  it('getComponentSchema returns full props for Table incl. the required binding props', () => {
    const t = getComponentSchema('Table');
    expect(t).toBeTruthy();
    const keys = t!.properties.map((p) => p.key);
    expect(keys).toContain('data');
    expect(keys).toContain('dataSourceSelector');
    expect(keys).toContain('autogenerateColumns');
    // dataSourceSelector's harvested default is the value that makes a Table render
    expect(t!.properties.find((p) => p.key === 'dataSourceSelector')?.default).toBe('rawJson');
  });

  it('returns null for an unknown component type', () => {
    expect(getComponentSchema('NotAComponent')).toBeNull();
  });

  it('excludes legacy dropdowns but keeps the V2s', () => {
    const types = getCatalog().map((c) => c.type);
    expect(types).not.toContain('DropDown');
    expect(types).not.toContain('Multiselect');
    expect(types).toContain('DropdownV2');
    expect(types).toContain('MultiselectV2');
  });

  it('serves curated renderingHints for Chart and Statistics', () => {
    const chart = getComponentSchema('Chart');
    expect(chart!.renderingHints).toBeTruthy();
    expect(String(chart!.renderingHints!.recommendedWidthCols)).toMatch(/13.?15/);
    expect(String(chart!.renderingHints!.note)).toMatch(/title/i);
    const stat = getComponentSchema('Statistics');
    expect(String(stat!.renderingHints!.recommendedMinHeightPx)).toMatch(/110.?120/);
    expect(String(stat!.renderingHints!.secondaryValueUsage)).toMatch(/narrow delta slot.*number or percentage/i);
    const modal = getComponentSchema('ModalV2');
    expect(modal!.renderingHints!.recommendedFieldAlignment).toBe('top');
    expect(String(modal!.renderingHints!.recommendedFieldRowStepPx)).toMatch(/70/);
  });

  it('serves the source-verified Table row-action Button-column contract', () => {
    const table = getComponentSchema('Table')!;
    const rowActions = table.authoringHints!.rowActionButtons as any;
    expect(rowActions.catalogActionsMeaning).toMatch(/runtime methods.*not row-action buttons/i);
    expect(rowActions.recommendedApproach).toMatch(/columnType="button".*deprecated/i);
    expect(rowActions.columnExample).toMatchObject({
      key: 'actions',
      columnType: 'button',
      autogenerated: false,
      buttons: [
        expect.objectContaining({
          id: 'view-action',
          buttonLabel: 'View',
          buttonType: 'solid',
          buttonVisibility: true,
        }),
      ],
    });
    expect(rowActions.eventExample).toMatchObject({
      source_type: 'table_column',
      ref: 'actions::view-action',
      trigger: 'onClick',
    });
  });

  it('keeps selective DropdownV2 schema lookups complete and exposes its runtime selection', () => {
    const dropdown = getComponentSchema('DropdownV2')!;
    const schema = dropdown.properties.find((property) => property.key === 'schema');
    const options = dropdown.properties.find((property) => property.key === 'options');
    expect(schema).toMatchObject({
      requires: { advanced: '{{true}}' },
      mutuallyExclusiveWith: ['options'],
    });
    expect(String(schema?.default)).not.toContain('…');
    expect(options).toMatchObject({
      requires: { advanced: '{{false}}' },
      mutuallyExclusiveWith: ['schema'],
    });
    expect(dropdown.exposedVariables?.map((variable) => variable.name)).toEqual(
      expect.arrayContaining(['value', 'selectedOption', 'options'])
    );
    expect((dropdown.authoringHints?.optionModes as any).rule).toMatch(/schema only when advanced=true/i);
  });

  it('keeps modal fields compact without losing the rendered-height rule', () => {
    const modalHints = getComponentSchema('ModalV2')!.renderingHints as any;
    expect(modalHints).toMatchObject({
      recommendedSingleLineFieldHeightPx: 40,
      topAlignedRenderedFootprintPx: 60,
      recommendedTextAreaHeightPx: '90–100',
    });
    expect(modalHints.recommendedFieldRowStepPx).toMatch(/70.*40px authored.*20px.*10px gap/i);

    const inputHints = getComponentSchema('TextInput')!.renderingHints as any;
    expect(inputHints.compactFormHeight).toMatch(/defaultSize\.height.*40px.*60px.*70px/i);
    expect(inputHints.valueTextSizing).toMatch(/does not enlarge.*value text.*labelFontSize/i);
  });

  it('serves the authoritative generated-Form field contract and FilePicker workaround', () => {
    const form = getComponentSchema('Form')!;
    const hints = form.authoringHints!.jsonSchemaFields as any;
    expect(hints.supportedTypes).toEqual(FORM_SCHEMA_FIELD_TYPES);
    expect(hints.safeGeneratedTypes).toEqual(SAFE_GENERATED_FORM_FIELD_TYPES);
    expect(hints.decisionRule).toMatch(/only when every field.*safeGeneratedTypes.*entire form.*standalone/i);
    expect(hints.selectContract).toMatch(/values.*displayValues.*not options/i);
    expect(hints.validationContract).toMatch(/no required flag.*minLength.*customRule/i);
    expect(hints.unsafeTypes.filepicker).toMatch(/crashes the entire Form.*standalone FilePicker/i);
    expect(hints.emptyDateValue).toBe('{{null}}');
    expect(hints.hardLayoutLimit).toMatch(/does not pass alignment.*TextArea.*literal "Label".*single-line/i);
    expect(hints.standaloneReplacement).toMatchObject({
      alignment: { path: 'styles.alignment.value', value: 'top' },
      requiredValidationPath: 'validation.mandatory',
      valuePath: 'components.<field>.value',
      fileValuePath: 'components.<picker>.file[0]',
    });
  });
});
