import { describe, expect, it } from 'vitest';
import { lintComponentSpec } from '../src/lint.js';

const rawData = '{{ queries.tickets.data.map(r => ({ subject: r.subject, created_at: r.created_at })) }}';
const rawColumn = {
  id: 'queue-sel-created_at', name: 'created_at', key: 'created_at',
  columnType: 'string', columnSize: 100, columnVisibility: false,
};
const table = (columns: Record<string, unknown>[], data = rawData) => ({
  name: 'queue', type: 'Table', properties: { data: { value: data }, columns: { value: columns } },
});
const timestampWarnings = (spec: Parameters<typeof lintComponentSpec>[0]) =>
  lintComponentSpec(spec).warnings.filter(w => w.includes('raw ISO timestamp'));

describe('Table timestamp display diagnostics exclude known-hidden raw selection fields', () => {
  it.each([false, '{{false}}'])('does not warn for canonical hidden visibility %s or rewrite raw selectedRow data', columnVisibility => {
    const spec = table([{ ...rawColumn, columnVisibility }]);
    const before = JSON.stringify(spec);
    expect(timestampWarnings(spec)).toEqual([]);
    expect(spec.properties.data.value).toContain('created_at: r.created_at');
    expect(JSON.stringify(spec)).toBe(before);
  });

  it.each([undefined, true, '{{true}}', '{{variables.showCreated}}', '{{ !variables.hideCreated }}', null, 0, 'false', { value: false }])
    ('retains the display warning when visibility is not canonically known hidden: %j', columnVisibility => {
      const { columnVisibility: _hidden, ...visibleColumn } = rawColumn;
      const spec = table([{ ...visibleColumn, ...(columnVisibility === undefined ? {} : { columnVisibility }) }]);
      expect(timestampWarnings(spec)).toEqual([expect.stringContaining('"created_at" looks date/time-like')]);
    });

  it('suppresses only the hidden column, not a visible timestamp in the same table', () => {
    const spec = table([rawColumn, { id: 'updated', name: 'Updated', key: 'updated_at', columnType: 'string' }]);
    expect(timestampWarnings(spec)).toEqual([expect.stringContaining('"updated_at" looks date/time-like')]);
  });

  it('keeps required-field, unsupported/deprecated-type and button-schema diagnostics for hidden columns', () => {
    const result = lintComponentSpec(table([
      { columnVisibility: false, columnType: 'string' },
      { ...rawColumn, columnType: 'date' },
      { ...rawColumn, id: 'legacy', key: 'legacy_at', columnType: 'tags' },
      { ...rawColumn, id: 'action', key: 'action', columnType: 'button' },
    ]));
    expect(result.warnings.join(' ')).toMatch(/missing `name`/);
    expect(result.warnings.join(' ')).toMatch(/missing `key`/);
    expect(result.errors.join(' ')).toContain('unsupported columnType:"date"');
    expect(result.errors.join(' ')).toContain('deprecated columnType:"tags"');
    expect(result.warnings.join(' ')).toContain('button column needs a non-empty `buttons` array');
  });

  it('preserves visible formatted-field exemptions and datepicker columns', () => {
    expect(timestampWarnings(table([{ ...rawColumn, columnVisibility: true }],
      '{{ queries.tickets.data.map(r => ({ created_at: moment(r.created_at).format("DD MMM YYYY") })) }}'))).toEqual([]);
    expect(timestampWarnings(table([{ ...rawColumn, key: 'created_display', columnVisibility: true }]))).toEqual([]);
    expect(timestampWarnings(table([{ ...rawColumn, columnVisibility: true, columnType: 'datepicker',
      dateFormat: 'DD MMM YYYY', parseDateFormat: 'YYYY-MM-DDTHH:mm:ssZ' }]))).toEqual([]);
  });

  it('does not suppress the separate visible KeyValuePair timestamp diagnostic', () => {
    expect(timestampWarnings({ name: 'details', type: 'KeyValuePair', properties: {
      data: { value: '{{variables.ticket}}' },
      fields: { value: [{ id: 'created', name: 'Created', key: 'created_at', fieldType: 'string', autogenerated: false }] },
    } })).toEqual([expect.stringContaining('fieldType:"string"')]);
  });
});
