/**
 * Component catalog, served from data/component-schemas.json (generated by
 * scripts/generate-catalog.mjs from ToolJet's widget definitions).
 * - getCatalog(): the lightweight palette — every component type + its purpose.
 * - getComponentSchema(type): the full property schema for one component (props with
 *   type + default, defaultSize, styles), so a caller can configure it without guessing.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

export interface ComponentProp {
  key: string;
  label?: string;
  valueType?: string;
  default?: unknown;
  /** Other component properties required for this property to take effect. */
  requires?: Record<string, unknown>;
  /** Properties that should not be authored together with this one. */
  mutuallyExclusiveWith?: string[];
}

export interface ComponentEvent {
  id: string;
  label?: string;
}

export interface ComponentAction {
  handle: string;
  displayName?: string;
  params?: Array<Record<string, unknown>>;
}

export interface ExposedVariable {
  name: string;
  default?: unknown;
}

export interface ComponentDefaultChild {
  componentName: string;
  slotName?: string;
  layout?: { top?: number; left?: number; width?: number; height?: number };
  properties?: string[];
  styles?: string[];
  defaultValue?: Record<string, unknown>;
  accessorKey?: string;
  incrementWidth?: number;
}

export interface ComponentSchema {
  type: string;
  name?: string;
  description?: string;
  defaultSize?: { width: number; height: number };
  properties: ComponentProp[];
  styles: ComponentProp[];
  /** Trigger ids accepted by add_events for this component. */
  events?: ComponentEvent[];
  /** Runtime methods accepted by control-component's componentSpecificActionHandle. */
  actions?: ComponentAction[];
  /** Values readable as components.<name>.<variable> at runtime. */
  exposedVariables?: ExposedVariable[];
  /** Built-in semantic child templates supplied by ToolJet. */
  defaultChildren?: ComponentDefaultChild[];
  /** Curated sizing/readability hints for components that have them (e.g. Chart, Statistics). */
  renderingHints?: Record<string, unknown>;
  /** Source-verified nested authoring contracts not represented by the flat property schema. */
  authoringHints?: Record<string, unknown>;
}

// Resolves to <repo>/data/... whether running from src (tsx) or dist (built).
const dataPath = resolve(dirname(fileURLToPath(import.meta.url)), '../data/component-schemas.json');

let cache: Record<string, ComponentSchema> | null = null;
function load(): Record<string, ComponentSchema> {
  if (!cache) cache = JSON.parse(readFileSync(dataPath, 'utf8')) as Record<string, ComponentSchema>;
  return cache;
}

/** The palette: every component's type + purpose (no per-prop detail). */
export function getCatalog(): Array<{ type: string; description?: string }> {
  return Object.values(load())
    .map((c) => ({ type: c.type, description: c.description }))
    .sort((a, b) => a.type.localeCompare(b.type));
}

/** The full property schema for one component type, or null if unknown. */
export function getComponentSchema(type: string): ComponentSchema | null {
  return load()[type] ?? null;
}
